service: pasale
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  versionFunctions: false
  apiGateway:
    shouldStartNameWithService: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
            - "s3:GetObject"
          Resource:
            - "arn:aws:s3:::pasale-content/*"

package:
  individually: true
  exclude:
      - backend/node_modules/**
      - frontend
      - node_modules/**

plugins:
  - serverless-finch

custom:
  client:
    bucketName: pasale
    distributionFolder: frontend/dist/pasale/
    errorDocument: index.html

functions:
  addItemsToDB:
    handler: backend/addItemToDB.addItemToDB
    events:
      - http:
          path: /addItemToDB
          method: GET
          cors: true

resources:
  Resources:
    PasaleContent:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: pasale-content

    BucketPolicyForPasaleContent:
      Type: "AWS::S3::BucketPolicy"
      Properties:
        PolicyDocument:
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: "*"
              Action:
                - "s3:GetObject"
                - "s3:PutObject"
              Resource: arn:aws:s3:::pasale-content/*
        Bucket:
          Ref: PasaleContent

    pasale:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: pasale
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
